export type OrderItem = {
  name?: string;
  title?: string;
  product_name?: string;
  nome?: string;
  type?: string;
  flavors?: string[];
  selected_flavors?: string[];
  size?: string;
  crust?: string;
  borda?: string;
  ingredients?: string | string[];
  additions?: any[];
  adicionais?: any[];
  price?: number | string;
  total_price?: number | string;
  unit_price?: number | string;
  total?: number | string;
  qty?: number;
  quantity?: number;
  notes?: string;
  observations?: string;
  observacao?: string;
  item_notes?: string;
};

export type Order = {
  id: string;
  order_number: number;
  tenant_id: string;
  customer_name: string;
  customer_phone: string;
  customer_address: string | null;
  neighborhood: string | null;
  items: OrderItem[] | unknown;
  total: number;
  delivery_fee: number;
  payment_method: string | null;
  change_for: number | null;
  notes: string | null;
  status: string;
  created_at: string;
  is_seen?: boolean;
  order_type?: string | null;
  service_mode?: string | null;
  fulfillment_type?: string | null;
  delivery_type?: string | null;
  table_number?: string | null;
  tableNumber?: string | null;
  mesa?: string | null;
  ticket_number?: string | null;
  payment_status?: string | null;
};
