/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrintOrderIdRouteImport } from './routes/print.$orderId'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as ApiPublicCreatePizzeriaRouteImport } from './routes/api/public/create-pizzeria'
import { Route as ApiPublicCreateOrderRouteImport } from './routes/api/public/create-order'
import { Route as ApiPizzeriasCreateRouteImport } from './routes/api/pizzerias.create'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin.users'
import { Route as AppAdminAnalyticsRouteImport } from './routes/_app/admin.analytics'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintOrderIdRoute = PrintOrderIdRouteImport.update({
  id: '/print/$orderId',
  path: '/print/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicCreatePizzeriaRoute = ApiPublicCreatePizzeriaRouteImport.update({
  id: '/api/public/create-pizzeria',
  path: '/api/public/create-pizzeria',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCreateOrderRoute = ApiPublicCreateOrderRouteImport.update({
  id: '/api/public/create-order',
  path: '/api/public/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPizzeriasCreateRoute = ApiPizzeriasCreateRouteImport.update({
  id: '/api/pizzerias/create',
  path: '/api/pizzerias/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAnalyticsRoute = AppAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/api/orders': typeof ApiOrdersRoute
  '/print/$orderId': typeof PrintOrderIdRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/api/pizzerias/create': typeof ApiPizzeriasCreateRoute
  '/api/public/create-order': typeof ApiPublicCreateOrderRoute
  '/api/public/create-pizzeria': typeof ApiPublicCreatePizzeriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/api/orders': typeof ApiOrdersRoute
  '/print/$orderId': typeof PrintOrderIdRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/api/pizzerias/create': typeof ApiPizzeriasCreateRoute
  '/api/public/create-order': typeof ApiPublicCreateOrderRoute
  '/api/public/create-pizzeria': typeof ApiPublicCreatePizzeriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/api/orders': typeof ApiOrdersRoute
  '/print/$orderId': typeof PrintOrderIdRoute
  '/_app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/api/pizzerias/create': typeof ApiPizzeriasCreateRoute
  '/api/public/create-order': typeof ApiPublicCreateOrderRoute
  '/api/public/create-pizzeria': typeof ApiPublicCreatePizzeriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/settings'
    | '/api/orders'
    | '/print/$orderId'
    | '/admin/analytics'
    | '/admin/users'
    | '/api/pizzerias/create'
    | '/api/public/create-order'
    | '/api/public/create-pizzeria'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin'
    | '/dashboard'
    | '/settings'
    | '/api/orders'
    | '/print/$orderId'
    | '/admin/analytics'
    | '/admin/users'
    | '/api/pizzerias/create'
    | '/api/public/create-order'
    | '/api/public/create-pizzeria'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/api/orders'
    | '/print/$orderId'
    | '/_app/admin/analytics'
    | '/_app/admin/users'
    | '/api/pizzerias/create'
    | '/api/public/create-order'
    | '/api/public/create-pizzeria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  PrintOrderIdRoute: typeof PrintOrderIdRoute
  ApiPizzeriasCreateRoute: typeof ApiPizzeriasCreateRoute
  ApiPublicCreateOrderRoute: typeof ApiPublicCreateOrderRoute
  ApiPublicCreatePizzeriaRoute: typeof ApiPublicCreatePizzeriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$orderId': {
      id: '/print/$orderId'
      path: '/print/$orderId'
      fullPath: '/print/$orderId'
      preLoaderRoute: typeof PrintOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/create-pizzeria': {
      id: '/api/public/create-pizzeria'
      path: '/api/public/create-pizzeria'
      fullPath: '/api/public/create-pizzeria'
      preLoaderRoute: typeof ApiPublicCreatePizzeriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/create-order': {
      id: '/api/public/create-order'
      path: '/api/public/create-order'
      fullPath: '/api/public/create-order'
      preLoaderRoute: typeof ApiPublicCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pizzerias/create': {
      id: '/api/pizzerias/create'
      path: '/api/pizzerias/create'
      fullPath: '/api/pizzerias/create'
      preLoaderRoute: typeof ApiPizzeriasCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/analytics': {
      id: '/_app/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AppAdminAnalyticsRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAnalyticsRoute: typeof AppAdminAnalyticsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAnalyticsRoute: AppAdminAnalyticsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  PrintOrderIdRoute: PrintOrderIdRoute,
  ApiPizzeriasCreateRoute: ApiPizzeriasCreateRoute,
  ApiPublicCreateOrderRoute: ApiPublicCreateOrderRoute,
  ApiPublicCreatePizzeriaRoute: ApiPublicCreatePizzeriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
