/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PresentationRouteImport } from './routes/presentation'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrintOrderIdRouteImport } from './routes/print.$orderId'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppMenuRouteImport } from './routes/_app/menu'
import { Route as AppFinanceRouteImport } from './routes/_app/finance'
import { Route as AppDocsRouteImport } from './routes/_app/docs'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppCombosRouteImport } from './routes/_app/combos'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as ApiPublicCreatePizzeriaRouteImport } from './routes/api/public/create-pizzeria'
import { Route as ApiPublicCreateOrderRouteImport } from './routes/api/public/create-order'
import { Route as ApiPizzeriasSyncMenuRouteImport } from './routes/api/pizzerias.sync-menu'
import { Route as ApiPizzeriasFiqonTestRouteImport } from './routes/api/pizzerias.fiqon-test'
import { Route as ApiPizzeriasCreateRouteImport } from './routes/api/pizzerias.create'
import { Route as AppAdminUsersRouteImport } from './routes/_app/admin.users'
import { Route as AppAdminAnalyticsRouteImport } from './routes/_app/admin.analytics'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PresentationRoute = PresentationRouteImport.update({
  id: '/presentation',
  path: '/presentation',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintOrderIdRoute = PrintOrderIdRouteImport.update({
  id: '/print/$orderId',
  path: '/print/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppMenuRoute = AppMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceRoute = AppFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCombosRoute = AppCombosRouteImport.update({
  id: '/combos',
  path: '/combos',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicCreatePizzeriaRoute = ApiPublicCreatePizzeriaRouteImport.update({
  id: '/api/public/create-pizzeria',
  path: '/api/public/create-pizzeria',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCreateOrderRoute = ApiPublicCreateOrderRouteImport.update({
  id: '/api/public/create-order',
  path: '/api/public/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPizzeriasSyncMenuRoute = ApiPizzeriasSyncMenuRouteImport.update({
  id: '/api/pizzerias/sync-menu',
  path: '/api/pizzerias/sync-menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPizzeriasFiqonTestRoute = ApiPizzeriasFiqonTestRouteImport.update({
  id: '/api/pizzerias/fiqon-test',
  path: '/api/pizzerias/fiqon-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPizzeriasCreateRoute = ApiPizzeriasCreateRouteImport.update({
  id: '/api/pizzerias/create',
  path: '/api/pizzerias/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminUsersRoute = AppAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppAdminRoute,
} as any)
const AppAdminAnalyticsRoute = AppAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/presentation': typeof PresentationRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/combos': typeof AppCombosRoute
  '/dashboard': typeof AppDashboardRoute
  '/docs': typeof AppDocsRoute
  '/finance': typeof AppFinanceRoute
  '/menu': typeof AppMenuRoute
  '/settings': typeof AppSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/orders': typeof ApiOrdersRoute
  '/print/$orderId': typeof PrintOrderIdRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/api/pizzerias/create': typeof ApiPizzeriasCreateRoute
  '/api/pizzerias/fiqon-test': typeof ApiPizzeriasFiqonTestRoute
  '/api/pizzerias/sync-menu': typeof ApiPizzeriasSyncMenuRoute
  '/api/public/create-order': typeof ApiPublicCreateOrderRoute
  '/api/public/create-pizzeria': typeof ApiPublicCreatePizzeriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/presentation': typeof PresentationRoute
  '/signup': typeof SignupRoute
  '/admin': typeof AppAdminRouteWithChildren
  '/combos': typeof AppCombosRoute
  '/dashboard': typeof AppDashboardRoute
  '/docs': typeof AppDocsRoute
  '/finance': typeof AppFinanceRoute
  '/menu': typeof AppMenuRoute
  '/settings': typeof AppSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/orders': typeof ApiOrdersRoute
  '/print/$orderId': typeof PrintOrderIdRoute
  '/admin/analytics': typeof AppAdminAnalyticsRoute
  '/admin/users': typeof AppAdminUsersRoute
  '/api/pizzerias/create': typeof ApiPizzeriasCreateRoute
  '/api/pizzerias/fiqon-test': typeof ApiPizzeriasFiqonTestRoute
  '/api/pizzerias/sync-menu': typeof ApiPizzeriasSyncMenuRoute
  '/api/public/create-order': typeof ApiPublicCreateOrderRoute
  '/api/public/create-pizzeria': typeof ApiPublicCreatePizzeriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/presentation': typeof PresentationRoute
  '/signup': typeof SignupRoute
  '/_app/admin': typeof AppAdminRouteWithChildren
  '/_app/combos': typeof AppCombosRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/docs': typeof AppDocsRoute
  '/_app/finance': typeof AppFinanceRoute
  '/_app/menu': typeof AppMenuRoute
  '/_app/settings': typeof AppSettingsRoute
  '/api/health': typeof ApiHealthRoute
  '/api/orders': typeof ApiOrdersRoute
  '/print/$orderId': typeof PrintOrderIdRoute
  '/_app/admin/analytics': typeof AppAdminAnalyticsRoute
  '/_app/admin/users': typeof AppAdminUsersRoute
  '/api/pizzerias/create': typeof ApiPizzeriasCreateRoute
  '/api/pizzerias/fiqon-test': typeof ApiPizzeriasFiqonTestRoute
  '/api/pizzerias/sync-menu': typeof ApiPizzeriasSyncMenuRoute
  '/api/public/create-order': typeof ApiPublicCreateOrderRoute
  '/api/public/create-pizzeria': typeof ApiPublicCreatePizzeriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/presentation'
    | '/signup'
    | '/admin'
    | '/combos'
    | '/dashboard'
    | '/docs'
    | '/finance'
    | '/menu'
    | '/settings'
    | '/api/health'
    | '/api/orders'
    | '/print/$orderId'
    | '/admin/analytics'
    | '/admin/users'
    | '/api/pizzerias/create'
    | '/api/pizzerias/fiqon-test'
    | '/api/pizzerias/sync-menu'
    | '/api/public/create-order'
    | '/api/public/create-pizzeria'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/presentation'
    | '/signup'
    | '/admin'
    | '/combos'
    | '/dashboard'
    | '/docs'
    | '/finance'
    | '/menu'
    | '/settings'
    | '/api/health'
    | '/api/orders'
    | '/print/$orderId'
    | '/admin/analytics'
    | '/admin/users'
    | '/api/pizzerias/create'
    | '/api/pizzerias/fiqon-test'
    | '/api/pizzerias/sync-menu'
    | '/api/public/create-order'
    | '/api/public/create-pizzeria'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/presentation'
    | '/signup'
    | '/_app/admin'
    | '/_app/combos'
    | '/_app/dashboard'
    | '/_app/docs'
    | '/_app/finance'
    | '/_app/menu'
    | '/_app/settings'
    | '/api/health'
    | '/api/orders'
    | '/print/$orderId'
    | '/_app/admin/analytics'
    | '/_app/admin/users'
    | '/api/pizzerias/create'
    | '/api/pizzerias/fiqon-test'
    | '/api/pizzerias/sync-menu'
    | '/api/public/create-order'
    | '/api/public/create-pizzeria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  PresentationRoute: typeof PresentationRoute
  SignupRoute: typeof SignupRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  PrintOrderIdRoute: typeof PrintOrderIdRoute
  ApiPizzeriasCreateRoute: typeof ApiPizzeriasCreateRoute
  ApiPizzeriasFiqonTestRoute: typeof ApiPizzeriasFiqonTestRoute
  ApiPizzeriasSyncMenuRoute: typeof ApiPizzeriasSyncMenuRoute
  ApiPublicCreateOrderRoute: typeof ApiPublicCreateOrderRoute
  ApiPublicCreatePizzeriaRoute: typeof ApiPublicCreatePizzeriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presentation': {
      id: '/presentation'
      path: '/presentation'
      fullPath: '/presentation'
      preLoaderRoute: typeof PresentationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$orderId': {
      id: '/print/$orderId'
      path: '/print/$orderId'
      fullPath: '/print/$orderId'
      preLoaderRoute: typeof PrintOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/menu': {
      id: '/_app/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof AppMenuRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/finance': {
      id: '/_app/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AppFinanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/docs': {
      id: '/_app/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/combos': {
      id: '/_app/combos'
      path: '/combos'
      fullPath: '/combos'
      preLoaderRoute: typeof AppCombosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/create-pizzeria': {
      id: '/api/public/create-pizzeria'
      path: '/api/public/create-pizzeria'
      fullPath: '/api/public/create-pizzeria'
      preLoaderRoute: typeof ApiPublicCreatePizzeriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/create-order': {
      id: '/api/public/create-order'
      path: '/api/public/create-order'
      fullPath: '/api/public/create-order'
      preLoaderRoute: typeof ApiPublicCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pizzerias/sync-menu': {
      id: '/api/pizzerias/sync-menu'
      path: '/api/pizzerias/sync-menu'
      fullPath: '/api/pizzerias/sync-menu'
      preLoaderRoute: typeof ApiPizzeriasSyncMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pizzerias/fiqon-test': {
      id: '/api/pizzerias/fiqon-test'
      path: '/api/pizzerias/fiqon-test'
      fullPath: '/api/pizzerias/fiqon-test'
      preLoaderRoute: typeof ApiPizzeriasFiqonTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pizzerias/create': {
      id: '/api/pizzerias/create'
      path: '/api/pizzerias/create'
      fullPath: '/api/pizzerias/create'
      preLoaderRoute: typeof ApiPizzeriasCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin/users': {
      id: '/_app/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AppAdminUsersRouteImport
      parentRoute: typeof AppAdminRoute
    }
    '/_app/admin/analytics': {
      id: '/_app/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AppAdminAnalyticsRouteImport
      parentRoute: typeof AppAdminRoute
    }
  }
}

interface AppAdminRouteChildren {
  AppAdminAnalyticsRoute: typeof AppAdminAnalyticsRoute
  AppAdminUsersRoute: typeof AppAdminUsersRoute
}

const AppAdminRouteChildren: AppAdminRouteChildren = {
  AppAdminAnalyticsRoute: AppAdminAnalyticsRoute,
  AppAdminUsersRoute: AppAdminUsersRoute,
}

const AppAdminRouteWithChildren = AppAdminRoute._addFileChildren(
  AppAdminRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRouteWithChildren
  AppCombosRoute: typeof AppCombosRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDocsRoute: typeof AppDocsRoute
  AppFinanceRoute: typeof AppFinanceRoute
  AppMenuRoute: typeof AppMenuRoute
  AppSettingsRoute: typeof AppSettingsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRouteWithChildren,
  AppCombosRoute: AppCombosRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDocsRoute: AppDocsRoute,
  AppFinanceRoute: AppFinanceRoute,
  AppMenuRoute: AppMenuRoute,
  AppSettingsRoute: AppSettingsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  PresentationRoute: PresentationRoute,
  SignupRoute: SignupRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  PrintOrderIdRoute: PrintOrderIdRoute,
  ApiPizzeriasCreateRoute: ApiPizzeriasCreateRoute,
  ApiPizzeriasFiqonTestRoute: ApiPizzeriasFiqonTestRoute,
  ApiPizzeriasSyncMenuRoute: ApiPizzeriasSyncMenuRoute,
  ApiPublicCreateOrderRoute: ApiPublicCreateOrderRoute,
  ApiPublicCreatePizzeriaRoute: ApiPublicCreatePizzeriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
