// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
// EDITADO em relação ao gerado: a leitura passa por resolveSupabaseEnv (./env.ts),
// que tolera aspas, espaços e domínio sem esquema. Reaplique se for regerado.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { resolveSupabaseEnv } from "./env";

function createSupabaseAdminClient() {
  const env = resolveSupabaseEnv(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY, {
    url: "SUPABASE_URL",
    key: "SUPABASE_SERVICE_ROLE_KEY",
  });

  if (!env.ok) {
    console.error(`[Supabase] ${env.message}`);
    throw new Error(env.message);
  }

  const { url: SUPABASE_URL, key: SUPABASE_SERVICE_ROLE_KEY } = env;

  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
